'use client';

import { Bell, Menu, Search, Settings, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';

export default function AdminHeader({ title, onMenuClick }: { title?: string; onMenuClick?: () => void }) {
  const [userName, setUserName] = useState('Admin');
  useEffect(() => { setUserName(localStorage.getItem('adminName') || localStorage.getItem('userName') || 'Admin'); }, []);
  return <header className="sticky top-0 z-30 border-b border-[#eadfd5] bg-[#fffaf5]/95 px-4 py-3 shadow-[0_1px_0_rgba(81,48,32,0.04)] backdrop-blur-xl sm:px-7"><div className="flex min-h-12 items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><button type="button" aria-label="Open admin navigation" onClick={onMenuClick} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-[#e3d7cc] bg-white text-[#685a50] lg:hidden"><Menu className="h-5 w-5" /></button><div className="min-w-0"><p className="hidden text-[11px] font-extrabold uppercase tracking-[0.14em] text-[#8b3a28] sm:block">Bandhan administration</p><h1 className="truncate text-lg font-extrabold tracking-tight text-[#211a16] sm:mt-0.5 sm:text-xl">{title || 'Dashboard'}</h1></div></div><div className="flex items-center gap-2.5"><div className="hidden h-11 w-72 items-center gap-2.5 rounded-xl border border-[#e3d7cc] bg-[#fbf5ef] px-3.5 xl:flex"><Search className="h-4.5 w-4.5 text-[#9a897e]" /><span className="text-sm text-[#8a7b70]">Search the control centre</span></div><button type="button" aria-label="Notifications" className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#e3d7cc] text-[#685a50] transition hover:border-[#b46a4d] hover:bg-[#fdf1eb] hover:text-[#8b3a28]"><Bell className="h-5 w-5" /></button><button type="button" aria-label="Settings" className="hidden h-11 w-11 items-center justify-center rounded-xl border border-[#e3d7cc] text-[#685a50] transition hover:border-[#b46a4d] hover:bg-[#fdf1eb] hover:text-[#8b3a28] sm:flex"><Settings className="h-5 w-5" /></button><div className="flex h-11 items-center gap-2 rounded-xl border border-[#e3d7cc] bg-white p-1.5 shadow-sm sm:pr-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f7e6dc] text-[#8b3a28]"><ShieldCheck className="h-4.5 w-4.5" /></span><span className="hidden max-w-32 truncate text-sm font-bold text-[#4a3d35] md:block">{userName}</span></div></div></div></header>;
}
