'use client';

import { Bell, Search, Settings, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';

export default function AdminHeader({ title }: { title?: string }) {
  const [userName, setUserName] = useState('Admin');
  useEffect(() => { setUserName(localStorage.getItem('adminName') || localStorage.getItem('userName') || 'Admin'); }, []);
  return <header className="sticky top-0 z-30 border-b border-[#eadfd5] bg-[#fffaf5]/95 px-5 py-3.5 shadow-[0_1px_0_rgba(81,48,32,0.04)] backdrop-blur-xl sm:px-7"><div className="flex min-h-12 items-center justify-between gap-4"><div className="min-w-0"><p className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-[#8b3a28]">Bandhan administration</p><h1 className="mt-0.5 truncate text-xl font-extrabold tracking-tight text-[#211a16]">{title || 'Dashboard'}</h1></div><div className="flex items-center gap-2.5"><div className="hidden h-11 w-72 items-center gap-2.5 rounded-xl border border-[#e3d7cc] bg-[#fbf5ef] px-3.5 lg:flex"><Search className="h-4.5 w-4.5 text-[#9a897e]" /><span className="text-sm text-[#8a7b70]">Search the control centre</span></div><button type="button" aria-label="Notifications" className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#e3d7cc] text-[#685a50] transition hover:border-[#b46a4d] hover:bg-[#fdf1eb] hover:text-[#8b3a28]"><Bell className="h-5 w-5" /></button><button type="button" aria-label="Settings" className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#e3d7cc] text-[#685a50] transition hover:border-[#b46a4d] hover:bg-[#fdf1eb] hover:text-[#8b3a28]"><Settings className="h-5 w-5" /></button><div className="flex h-11 items-center gap-2 rounded-xl border border-[#e3d7cc] bg-white py-1.5 pl-1.5 pr-3 shadow-sm"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f7e6dc] text-[#8b3a28]"><ShieldCheck className="h-4.5 w-4.5" /></span><span className="hidden max-w-32 truncate text-sm font-bold text-[#4a3d35] sm:block">{userName}</span></div></div></div></header>;
}
