'use client';

import { Bell, Menu, Search, Settings, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';

export default function AdminHeader({ title, onMenuClick }: { title?: string; onMenuClick?: () => void }) {
  const [userName, setUserName] = useState('Admin');
  useEffect(() => { setUserName(localStorage.getItem('adminName') || localStorage.getItem('userName') || 'Admin'); }, []);
  return <header className="sticky top-0 z-30 border-b border-[var(--bhn-border)] bg-white/95 px-4 py-2.5 backdrop-blur-xl sm:px-7"><div className="flex min-h-12 items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><button type="button" aria-label="Open admin navigation" onClick={onMenuClick} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-[var(--bhn-border)] bg-white text-[var(--bhn-text-muted)] lg:hidden"><Menu className="h-5 w-5" /></button><div className="min-w-0"><p className="hidden text-[10px] font-extrabold uppercase tracking-[0.14em] text-[var(--bhn-brand-700)] sm:block">Bandhan administration</p><h1 className="truncate text-lg font-extrabold tracking-tight text-[var(--bhn-text)] sm:text-xl">{title || 'Dashboard'}</h1></div></div><div className="flex items-center gap-2"><div className="hidden h-10 w-72 items-center gap-2.5 rounded-lg border border-[var(--bhn-border)] bg-[var(--bhn-surface-2)] px-3.5 xl:flex"><Search className="h-4 w-4 text-[var(--bhn-text-soft)]" /><span className="text-sm text-[var(--bhn-text-muted)]">Search the control centre</span></div><button type="button" aria-label="Notifications" className="flex h-10 w-10 items-center justify-center rounded-lg text-[var(--bhn-text-muted)] transition hover:bg-[var(--bhn-surface-2)] hover:text-[var(--bhn-brand-700)]"><Bell className="h-5 w-5" /></button><button type="button" aria-label="Settings" className="hidden h-10 w-10 items-center justify-center rounded-lg text-[var(--bhn-text-muted)] transition hover:bg-[var(--bhn-surface-2)] hover:text-[var(--bhn-brand-700)] sm:flex"><Settings className="h-5 w-5" /></button><div className="flex h-10 items-center gap-2 border-l border-[var(--bhn-border)] pl-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[var(--bhn-brand-50)] text-[var(--bhn-brand-700)]"><ShieldCheck className="h-4 w-4" /></span><span className="hidden max-w-32 truncate text-sm font-bold text-[var(--bhn-text)] md:block">{userName}</span></div></div></div></header>;
}
