'use client';

import { useMemo, useState } from 'react';
import { Edit, Plus, Search, Trash2 } from 'lucide-react';
import { type AdminService, useCreateServiceMutation, useDeleteServiceMutation, useGetServicesQuery, useGetUsersQuery, useUpdateServiceMutation } from '@/lib/adminApi';

const empty = { sellerId: '', sellerEmail: '', title: '', category: 'venue' as AdminService['category'], price: '', description: '', location: '', eventType: '', images: '', status: 'active' as AdminService['status'], isActive: true, isFeatured: false };
export default function Services() {
  const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [search, setSearch] = useState('');
  const { data: services = [] } = useGetServicesQuery(); const { data: users = [] } = useGetUsersQuery(); const [createService, { isLoading: creating }] = useCreateServiceMutation(); const [updateService, { isLoading: updating }] = useUpdateServiceMutation(); const [deleteService] = useDeleteServiceMutation();
  const filtered = useMemo(() => services.filter((s) => `${s.title} ${s.category} ${s.location}`.toLowerCase().includes(search.toLowerCase())), [services, search]);
  const reset = () => { setForm(empty); setEditingId(null); setShowForm(false); };
  const edit = (s: AdminService) => { setForm({ sellerId: s.sellerId, sellerEmail: s.sellerEmail, title: s.title, category: s.category, price: String(s.price), description: s.description, location: s.location, eventType: s.eventType, images: s.images.join(', '), status: s.status, isActive: s.isActive, isFeatured: s.isFeatured }); setEditingId(s._id); setShowForm(true); };
  const save = async () => { if (!form.title.trim() || (!editingId && !form.sellerId)) return; const body = { ...form, title: form.title.trim(), price: Number(form.price) || 0, images: form.images.split(',').map((x) => x.trim()).filter(Boolean) }; if (body.images.length < 4) { alert('At least four image URLs are required.'); return; } try { if (editingId) await updateService({ id: editingId, ...body }).unwrap(); else await createService(body).unwrap(); reset(); } catch (e) { console.error(e); } };
  return <div><div className="mb-4 flex items-center justify-between"><h1 className="admin-page-heading">Service Management</h1><button className="admin-btn admin-btn-primary" onClick={() => setShowForm(true)}><Plus className="h-3.5 w-3.5" />Add Service</button></div>
    {showForm && <div className="card mb-4 space-y-3"><div className="flex justify-between"><h2 className="text-sm font-semibold">{editingId ? 'Edit Service' : 'Add Service'}</h2><button className="admin-btn admin-btn-secondary" onClick={reset}>Cancel</button></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2"><select className="admin-input" value={form.sellerId} disabled={Boolean(editingId)} onChange={(e) => { const user = users.find((u) => u.id === e.target.value); setForm({ ...form, sellerId: e.target.value, sellerEmail: user?.email || '' }); }}><option value="">Select seller *</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name} ({u.email})</option>)}</select><input className="admin-input" placeholder="Service title *" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/><select className="admin-input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as AdminService['category'] })}><option value="venue">Venue</option><option value="catering">Catering</option><option value="decor">Decor</option></select><input className="admin-input" type="number" placeholder="Price" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })}/><input className="admin-input" placeholder="Location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })}/><input className="admin-input" placeholder="Event type" value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value })}/><input className="admin-input md:col-span-2" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/><input className="admin-input md:col-span-2" placeholder="Image URLs (comma-separated)" value={form.images} onChange={(e) => setForm({ ...form, images: e.target.value })}/></div><div className="flex gap-4 text-sm"><label><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} /> Active</label><label><input type="checkbox" checked={form.isFeatured} onChange={(e) => setForm({ ...form, isFeatured: e.target.checked })} /> Featured</label></div><button disabled={creating || updating} onClick={save} className="admin-btn admin-btn-primary">{creating || updating ? 'Saving...' : editingId ? 'Save Changes' : 'Create Service'}</button></div>}
    <div className="card mb-3 flex items-center"><Search className="mr-2 h-4 w-4 text-gray-400"/><input className="flex-1 outline-none" placeholder="Search services..." value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="card overflow-x-auto"><table className="admin-table w-full"><thead><tr><th>Service</th><th>Category</th><th>Location</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((s) => <tr key={s._id}><td className="font-medium text-sm">{s.title}</td><td>{s.category}</td><td>{s.location || '—'}</td><td>₹{s.price.toLocaleString()}</td><td>{s.isActive ? 'Active' : 'Inactive'}</td><td><div className="flex gap-1"><button className="admin-btn admin-btn-secondary" onClick={() => edit(s)}><Edit className="h-3 w-3"/></button><button className="admin-btn admin-btn-danger" onClick={() => { if (confirm('Delete this service?')) deleteService(s._id); }}><Trash2 className="h-3 w-3"/></button></div></td></tr>)}</tbody></table></div></div>;
}
