import { ArrowUpRight, BookOpen, BriefcaseBusiness, LayoutDashboard, ShoppingBag, Sparkles, Store, UsersRound } from "lucide-react";

const portals = [
  { title: "Marketplace", copy: "Products, rentals, services and venues for every gathering.", href: "/products", icon: ShoppingBag, tone: "var(--bhn-brand-50)" },
  { title: "Careers", copy: "Find meaningful work or build a stronger hiring pipeline.", href: "https://bandhan-jobs.vercel.app/Jobseeker/jobs", icon: BriefcaseBusiness, tone: "var(--bhn-surface-2)" },
  { title: "Learning", copy: "Learn event skills from trusted instructors at your pace.", href: "https://bandhan-student-two.vercel.app/student/allcourse", icon: BookOpen, tone: "var(--bhn-success-50)" },
  { title: "Sell with Bandhan", copy: "Manage products, services, quotes and business growth.", href: "https://product-seller-vert.vercel.app/login", icon: Store, tone: "var(--bhn-info-50)" },
  { title: "Create & teach", copy: "Build a course and grow a community of learners.", href: "https://bandhan-student-two.vercel.app/instructor", icon: LayoutDashboard, tone: "var(--bhn-neutral-100)" },
  { title: "Hire talent", copy: "Post roles and build your next great team.", href: "https://bandhan-jobs.vercel.app/jobposter/dashboard", icon: UsersRound, tone: "var(--bhn-error-50)" },
];

export default function PortalShowcase() {
  return <section id="portals" className="scroll-mt-20 bg-[var(--bhn-brand-950)] px-4 py-16 text-[var(--bhn-text-on-brand)] sm:px-6 md:py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.17em] text-[var(--bhn-brand-300)]">Choose your journey</p><h2 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">Every Bandhan portal, in one considered introduction.</h2><p className="mt-4 leading-7 opacity-70">Whether you are planning an occasion, learning a skill, finding work or growing a business, choose the space designed for you.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{portals.map(({ title, copy, href, icon: Icon, tone }) => <a key={title} href={href} target="_blank" rel="noreferrer" className="bhn-card bhn-card-hover group min-h-56 p-6 text-[var(--bhn-text)]" style={{ background: tone }}><Icon size={26} className="bhn-icon-tile" /><h3 className="mt-12 text-2xl font-semibold text-[var(--bhn-text)]">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--bhn-text-muted)]">{copy}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-[var(--bhn-brand-700)]">Open portal <ArrowUpRight size={16} className="transition group-hover:-translate-y-1 group-hover:translate-x-1" /></span></a>)}</div><div className="mt-8 flex items-center gap-3 rounded-2xl border border-[color:rgba(255,255,255,0.15)] bg-white/5 px-5 py-4 text-sm opacity-80"><Sparkles size={18} className="text-[var(--bhn-brand-300)]"/> Explore listings from the menu whenever you want; this page is your introduction to the complete Bandhan ecosystem.</div></div></section>;
}