import "@bandhan/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk, Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";
import RouteGuard from "@/components/auth/RouteGuard";

const manrope = Manrope({
  variable: "--bhn-font-sans",
  subsets: ["latin"],
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  variable: "--bhn-font-display",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${spaceGrotesk.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col" style={{ fontFamily: "var(--bhn-font-sans)" }} suppressHydrationWarning>
        <RouteGuard>{children}</RouteGuard>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}