export type CatalogItem = {
  id: string;
  title: string;
  category: string;
  description: string;
  price: number;
  priceLabel: string;
  rating: number;
  reviews: number;
  image: string;
  location: string;
  badge: string;
  href: string;
  meta: string;
};

export const productCatalog: CatalogItem[] = [
  {
    id: "invitation-suite",
    title: "Royal Invitation Suite",
    category: "Invitations",
    description: "Foil-accent printed invitations with matching RSVP cards and envelopes.",
    price: 3200,
    priceLabel: "₹3,200 / 100 pcs",
    rating: 4.8,
    reviews: 84,
    image: "/invitation.png",
    location: "Mumbai",
    badge: "Popular",
    href: "/userdashboard/cart",
    meta: "Ships in 5 days",
  },
  {
    id: "spice-favor-box",
    title: "Artisan Spice Favor Box",
    category: "Return Gifts",
    description: "Curated spice keepsakes for event guests and festive gatherings.",
    price: 1800,
    priceLabel: "₹1,800 / 25 boxes",
    rating: 4.7,
    reviews: 62,
    image: "/spice.png",
    location: "Jaipur",
    badge: "Handmade",
    href: "/userdashboard/cart",
    meta: "Custom labels",
  },
  {
    id: "ceremony-ring-tray",
    title: "Ceremony Ring Tray",
    category: "Accessories",
    description: "Minimal brass and floral ring tray for engagement and event rituals.",
    price: 2450,
    priceLabel: "₹2,450",
    rating: 4.9,
    reviews: 41,
    image: "/ring.png",
    location: "Delhi NCR",
    badge: "Limited",
    href: "/userdashboard/cart",
    meta: "Ready stock",
  },
  {
    id: "copper-lantern-set",
    title: "Copper Lantern Set",
    category: "Decor Rentals",
    description: "Warm metallic lanterns for aisle styling, table corners, and lounge areas.",
    price: 5200,
    priceLabel: "₹5,200 / event",
    rating: 4.6,
    reviews: 58,
    image: "/Copper.jpg",
    location: "Bengaluru",
    badge: "Rental",
    href: "/userdashboard/cart",
    meta: "Set of 18",
  },
  {
    id: "bohemian-runner",
    title: "Bohemian Table Runner",
    category: "Table Styling",
    description: "Textured runner set for haldi brunches, mehendi lunches, and intimate dinners.",
    price: 3900,
    priceLabel: "₹3,900 / 10 tables",
    rating: 4.5,
    reviews: 35,
    image: "/Bohemian.png",
    location: "Pune",
    badge: "New",
    href: "/userdashboard/cart",
    meta: "Earth palette",
  },
  {
    id: "premium-gift-hamper",
    title: "Premium Guest Hamper",
    category: "Return Gifts",
    description: "A refined hamper with sweets, keepsakes, and a personalized note card.",
    price: 6800,
    priceLabel: "₹6,800 / 20 hampers",
    rating: 4.9,
    reviews: 77,
    image: "/premium.png",
    location: "Hyderabad",
    badge: "Premium",
    href: "/userdashboard/cart",
    meta: "Personalized",
  },
];

export const serviceCatalog: CatalogItem[] = [
  {
    id: "premium-event-decor",
    title: "Premium Event Decoration",
    category: "Event Decor",
    description: "Full-stage florals, warm lighting, aisle styling, and setup coordination.",
    price: 25000,
    priceLabel: "From ₹25,000",
    rating: 4.8,
    reviews: 128,
    image: "/Border.png",
    location: "Mumbai, Delhi, Bengaluru",
    badge: "Featured",
    href: "/products/Services",
    meta: "3 design concepts",
  },
  {
    id: "bridal-makeup",
    title: "Bridal Makeup Artist",
    category: "Beauty",
    description: "HD bridal makeup, hairstyling, draping, and pre-event skin prep support.",
    price: 35000,
    priceLabel: "From ₹35,000",
    rating: 4.7,
    reviews: 96,
    image: "/makeup.png",
    location: "Delhi NCR",
    badge: "Verified",
    href: "/products/Services",
    meta: "Trial available",
  },
  {
    id: "photo-film",
    title: "Photography & Film",
    category: "Photography",
    description: "Candid photography, cinematic reels, drone moments, and edited albums.",
    price: 75000,
    priceLabel: "From ₹75,000",
    rating: 4.9,
    reviews: 143,
    image: "/photoshot.png",
    location: "Pan India",
    badge: "Top Rated",
    href: "/products/Services",
    meta: "2-day coverage",
  },
  {
    id: "fine-dining-catering",
    title: "Fine Dining Catering",
    category: "Catering",
    description: "Curated event menus, live counters, dessert bars, and service staff.",
    price: 1200,
    priceLabel: "From ₹1,200 / plate",
    rating: 4.6,
    reviews: 88,
    image: "/vendor3.jpg",
    location: "Jaipur",
    badge: "Chef Led",
    href: "/products/Services",
    meta: "Veg and non-veg",
  },
  {
    id: "venue-styling",
    title: "Venue Styling Consultation",
    category: "Planning",
    description: "Moodboards, vendor coordination, floor plan guidance, and decor budgeting.",
    price: 18000,
    priceLabel: "From ₹18,000",
    rating: 4.5,
    reviews: 54,
    image: "/modern.png",
    location: "Online + onsite",
    badge: "Flexible",
    href: "/userdashboard/quote",
    meta: "7-day plan",
  },
  {
    id: "mehendi-haldi",
    title: "Haldi & Mehendi Setup",
    category: "Pre-event",
    description: "Color-rich decor, seating, floral props, welcome signage, and music support.",
    price: 22000,
    priceLabel: "From ₹22,000",
    rating: 4.8,
    reviews: 73,
    image: "/flower.png",
    location: "Pune",
    badge: "Seasonal",
    href: "/products/Services",
    meta: "Outdoor ready",
  },
];

export const venueCatalog: CatalogItem[] = [
  {
    id: "taj-jaipur",
    title: "The Taj Hotel",
    category: "Luxury Hotel",
    description: "Heritage-inspired event spaces with premium hospitality and indoor banquet options.",
    price: 450000,
    priceLabel: "From ₹4,50,000",
    rating: 4.9,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
    location: "Jaipur",
    badge: "Premium",
    href: "/products/Venue/details",
    meta: "Up to 380 guests",
  },
  {
    id: "udaipur-palace",
    title: "Udaipur Palace Lawn",
    category: "Palace Venue",
    description: "Grand open-air lawns, lake-facing photo spots, and destination event support.",
    price: 650000,
    priceLabel: "From ₹6,50,000",
    rating: 4.8,
    reviews: 94,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80",
    location: "Udaipur",
    badge: "Destination",
    href: "/products/Venue/details",
    meta: "Up to 520 guests",
  },
  {
    id: "mumbai-banquet",
    title: "Aster Grand Banquet",
    category: "Banquet Hall",
    description: "Modern banquet hall with stage lighting, valet support, and flexible catering tie-ups.",
    price: 280000,
    priceLabel: "From ₹2,80,000",
    rating: 4.6,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=80",
    location: "Mumbai",
    badge: "Popular",
    href: "/products/Venue/details",
    meta: "Up to 300 guests",
  },
  {
    id: "goa-resort",
    title: "Coconut Grove Resort",
    category: "Beach Resort",
    description: "Resort event venue with poolside events, beach ceremonies, and guest stay packages.",
    price: 720000,
    priceLabel: "From ₹7,20,000",
    rating: 4.7,
    reviews: 68,
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=900&q=80",
    location: "Goa",
    badge: "Beach",
    href: "/products/Venue/details",
    meta: "Up to 250 guests",
  },
  {
    id: "delhi-farmhouse",
    title: "Meadow Stone Farmhouse",
    category: "Farmhouse",
    description: "Green outdoor venue for mehendi, haldi, and evening receptions with decor flexibility.",
    price: 190000,
    priceLabel: "From ₹1,90,000",
    rating: 4.5,
    reviews: 53,
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80",
    location: "Delhi NCR",
    badge: "Outdoor",
    href: "/products/Venue/details",
    meta: "Up to 420 guests",
  },
  {
    id: "bengaluru-garden",
    title: "Ivory Garden Pavilion",
    category: "Garden Venue",
    description: "Elegant garden pavilion with covered dining, floral pathways, and rain backup.",
    price: 340000,
    priceLabel: "From ₹3,40,000",
    rating: 4.6,
    reviews: 82,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=80",
    location: "Bengaluru",
    badge: "Verified",
    href: "/products/Venue/details",
    meta: "Up to 360 guests",
  },
];
