import type { Metadata } from "next";
import { Space_Grotesk, Manrope } from "next/font/google";
import "@bandhan/ui/styles.css";
import "./globals.css";
import ReduxProvider from "@/app/redux/provider";
import RouteGuard from "@/components/auth/RouteGuard";
import { Toaster } from "react-hot-toast";

const manrope = Manrope({
  variable: "--bhn-font-sans",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--bhn-font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col bg-[var(--bhn-bg)] text-[var(--bhn-text)] font-[var(--bhn-font-sans)]"
        suppressHydrationWarning
      >
        <ReduxProvider>
          <RouteGuard>{children}</RouteGuard>
        </ReduxProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
